-- Insertsd para testes 

insert into tbl_fornecedor values
(default,'11462614000373', 'PremieR Pet'), -- 1
(default,'04707195000327', 'Farmina Pet'),  -- 2
(default, '29737368003649', 'MARS BRASIL'); -- 3

insert into tbl_contatofornecedor values
(default, '1136547856', 'Julio Cesar', '1'),
(default, '1139914383', 'Clayton Ribeiro', '2'),
(default, '1139724522', 'Paloma Brito', '3');

insert into tbl_enderecofornecedor values
(default, 'Charles Goodyear, 712 Galpao100 Modulos a - B Lote Cururuquara Quadragleba B Unif 0', 'Cururuquara', '06524115', '2', 'Filial', '1', 'Santana de Parnaiba'),
(default, 'dos Pires, 5285, Galpao37 38 e 39 Bloco a Cond Ind. Sp Empresarial','Rio Abaixo', '12952361', '7', 'Filial', '2', 'Atibaia'), 
(default, 'Doutor Rafael de Barros, 209, Conj: 81 e 82; Cond: Ed. Varicred Iii', 'Paraiso', '04003041', '1', 'Filial', '3', 'Sao Paulo');

insert into tbl_produto values -- premier renal
(default, '1', 'PremieR Nutrição Clínica Obesidade Gatos é um alimento coadjuvante indicado para gatos adultos com excesso de peso para a obtenção do peso ideal ou por toda vida do animal quando recomendado pelo médico-veterinário nutrólogo. Pode ser também indicado nos casos de constipação responsiva a fibras. Este produto deve ser utilizado como auxiliar, portanto não substitui o tratamento convencional. PremieR Nutrição Clínica Obesidade Gatos é contraindicado para filhotes, fêmeas gestantes ou lactantes e para gatos que necessitem de maior aporte calórico. Este alimento deve ser utilizado sob prescrição e supervisão profissional', '10', '1', 'Alimentos Coadjuvantes', 'Variados', '', '','', 'Farinha de vísceras de frango, farinha de torresmo, glúten de milho, glúten de trigo, plasma sanguíneo desidratado de suíno, celulose, ervilha moída desidratada, quirera de arroz, polpa desidratada de beterraba, gordura de frango, óleo refinado de peixe, hidrolisado de fígado de suíno, acácia nilótica, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, cloreto de potássio, cloreto de sódio, cúrcuma (Curcuma longa), fosfatidilcolina, gelatina hidrolisada, L-carnitina, levedura de cervejaria inativada desidratada, metionina, sulfato de amônio, taurina, acetato de DL-alfa-tocoferol, acetato de retinol, ácido ascórbico monofosfato, ácido fólico, ácido pantotênico, biotina, bissulfito de menadiona nicotinamida, cianocobalamina, cloreto de colina, colecalciferol, niacina (ácido nicotínico), piridoxina, riboflavina, tiamina, ferro aminoácido quelato, iodeto de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato.
Contém glúten de milho transgênico (espécies doadoras de gene: Bacillus thuringiensis e/ou Agrobacterium tumefaciens e/ou Streptomyces viridochromogenes e/ou Zea mays)', '99.99', 'Catbuddy\premierobesidade.png', 'PremieR Nutrição Clínica Obesidade'),
(default, '1', 'PremieR Nutrição Clínica Gatos Renal é um alimento Super Premium auxiliar ao tratamento da doença renal crônica dos gatos. Além do tratamento prescrito pelo médico veterinário, algumas alterações na alimentação podem ser benéficas para pacientes com doença renal crônica.Os objetivos da dieta são minimizar os sintomas decorrentes da retenção de substâncias tóxicas e perda de elementos importantes na urina, diminuir a progressão da doença, proteger o tecido renal que ainda permanece saudável e prevenir a formação de cálculos urinários de oxalato de cálcio. Para doença renal crônica, este alimento deve ser utilizado sob orientação e prescrição de um profissional como único alimento por toda a vida do animal.',
'20', '1', 'Alimentos Coadjuvantes', 'Variados', '', '', '', 'Proteína hidrolisada de frango, farinha de torresmo, glúten de milho, proteína isolada de soja, plasma sanguíneo desidratado de suíno, grão de milho, quirera de arroz, polpa desidratada de beterraba, banha refinada, gordura de frango, óleo refinado de peixe, carbonato de cálcio, citrato de potássio, cloreto de potássio, cloreto de sódio, acácia nilótica, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cúrcuma (Curcuma longa), DL-metionina, fosfatidilcolina, frutooligossacarídeos, hidrolisado de fígado de suíno, levedura de cervejaria inativada desidratada, L-lisina, taurina, acetato de DL-alfa-tocoferol, acetato de retinol, ácido ascórbico monofosfato, ácido fólico, ácido pantotênico, biotina, bissulfito de menadiona nicotinamida, cianocobalamina, cloreto de colina, colecalciferol, niacina (ácido nicotínico), piridoxina, riboflavina, tiamina, iodeto de cálcio, ferro aminoácido quelato, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato. Contém grão de milho e glúten de milho transgênicos (espécies doadoras de gene: Bacillus thuringiensis e/ou Agrobacterium tumefaciens e/ou Streptomyces viridochromogenes e/ou Zea mays).',
'99.90', 'Catbuddy\premierrenal.png', 'PremieR Nutrição Clínica Gatos Renal'),
(default, '1', 'PremieR Nutrição Clínica Renal Gatos – Estágios Iniciais é um alimento coadjuvante indicado para gatos adultos com doença renal crônica nos estágios iniciais. Por se tratar de um alimento completo e balanceado, este produto também pode ser recomendado para gatos adultos em manutenção como cuidado renal precoce ou a critério do médico-veterinário. Além do tratamento prescrito pelo médico-veterinário, algumas alterações na alimentação podem ser benéficas para os pacientes com Doença Renal Crônica. Pensando nisso, PremieR Nutrição Clínica Renal Gatos – Estágios Iniciais apresenta teor reduzido de fósforo para auxiliar na manutenção da função renal e na prevenção do hiperparatireoidismo secundário renal, nível ótimo de proteína para contribuir na manutenção da massa magra, altos teores de EPA e DHA para proporcionar efeito renoprotetor e associação de fibras e prebióticos para favorecer a saúde intestinal. Este alimento deve ser utilizado sob orientação e prescrição de um profissional. É contraindicado para filhotes, fêmeas gestantes ou lactantes, nos casos em que há necessidade de restrição proteica e nos estágios avançados da doença renal crônica.',
'30', '1', 'Alimentos Coadjuvantes', 'Variados', '', '', '', 'Proteína hidrolisada de frango, albumina de ovo, farinha de torresmo, farinha de vísceras de frango, glúten de milho, proteína isolada de soja, quirera de arroz, fibra de cana-de-açúcar, polpa desidratada de beterraba, banha refinada, gordura de frango, óleo refinado de peixe, cloreto de potássio, cloreto de sódio, sulfato de cálcio dihidratado, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, fosfatidilcolina, frutooligossacarídeos, galactooligossacarídeos, hidrolisado de fígado de suíno, levedura autolisada de cana-de-açúcar, L-lisina, parede celular de levedura (fonte de mananoligossacarídeos), sulfato de amônio, taurina, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina H, vitamina K3, ferro aminoácido quelato, iodato de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato. Contém glúten de milho transgênico (espécies doadoras de gene: Bacillus thuringiensis e/ou Agrobacterium tumefaciens e/ou Streptomyces viridochromogenes e/ou Zea mays).',
'99.99', 'Catbuddy\premierrenalinicial.png', 'PremieR Nutrição Clínica Gatos Adultos Renal Estágios Iniciais'),
(default, '1', 'PremieR Nutrição Clínica Gatos Urinário Estruvita é um alimento Super Premium auxiliar ao tratamento dos cálculos urinários de estruvita. Algumas alterações na alimentação podem ser benéficas em pacientes com cálculos urinários. Os objetivos da dieta são controlar o pH urinário, diminuir a ingestão e excreção urinária de substâncias formadoras de cálculo e auxiliar na dissolução dos cálculos já formados.
Este alimento deve ser utilizado como único alimento, em geral, pelo período de 4 a 5 semanas podendo variar de acordo com o animal, sempre sob orientação e prescrição de um profissional.',
'15', '1', 'Alimentos Coadjuvantes', 'Variados', '', '', '', 'Farinha de vísceras de frango, farinha de torresmo, glúten de milho, plasma sanguíneo desidratado de suíno, proteína isolada de soja, grão de milho, grão de trigo, celulose, quirera de arroz, polpa desidratada de beterraba, banha refinada, gordura de frango, óleo refinado de peixe, ácido cítrico, cloreto de amônio, cloreto de potássio, cloreto de sódio, acácia nilótica, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cúrcuma (Curcuma longa), DL-metionina, fosfatidilcolina, hidrolisado de fígado de suíno, levedura de cervejaria inativada desidratada, L-lisina, sulfato de amônio, sulfato de glicosamina, taurina, acetato de DL-alfa-tocoferol, acetato de retinol, ácido ascórbico monofosfato, ácido fólico, ácido pantotênico, biotina, bissulfito de menadiona nicotinamida, cianocobalamina, cloreto de colina, colecalciferol, niacina (ácido nicotínico), piridoxina, riboflavina, tiamina, iodeto de cálcio, ferro aminoácido quelato, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato. Contém grão de milho e glúten de milho transgênicos* (espécies doadoras de gene: Bacillus thuringiensis e/ou Agrobacterium tumefaciens e/ou Streptomyces viridochromogenes e/ou Zea mays).',
'99.99', 'Catbuddy\premierurinarioestruvita.png', 'PremieR Nutrição Clínica Gatos Urinário Estruvita'); 


insert into tbl_produto values -- matisse
(default, '1', 'Matisse Carne & Arroz é um alimento completo e balanceado para gatos adultos com nível de atividade física normal.
As proteínas são provenientes de ingredientes nobres de alto valor biológico e o cozimento ideal dos carboidratos fornecem alta digestibilidade. A cobertura e inserção de óleos e palatabilizantes a vácuo - sistema utilizado, atualmente, apenas pela Farmina no mercado Pet Brasileiro - torna o produto extremamente palatável e de imediata aceitação. Além disso, garante-se uma ótima relação de ácidos graxos ômega 6 e 3, essencial para a saúde da pele e do pelo.
Matisse Carne & Arroz contém quantidade ideal de taurina, importante aminoácido para o bom desempenho do miocárdio e da visão. A dieta é complementada pelo aporte de todas as vitaminas e minerais necessários para uma alimentação completa e balanceada.',
'30', '2', 'Adulto', 'Carne e Arroz', '','','', 'farinha de carne e ossos de bovino, farinha de vísceras de aves, quirera de arroz, grãos de milho, grãos de sorgo, farinha de peixe, óleo de frango, polpa de beterraba, óleo de peixe, glúten de milho-60, ovo desidratado, levedura seca de cervejaria, DL-metionina, taurina, hidrolisado de fígado de frango e suíno, vitaminas (A, D3, E, B1, B2, B6, B12, C, biotina, niacina, ácido pantotênico, ácido fólico, cloreto de colina), cloreto de sódio, cloreto de potássio, ácido fosfórico, sulfato ferroso, sulfato de cobre, sulfato de zinco, sulfato de manganês, selenito de sódio, iodato de cálcio, sulfato de cobalto, propionato de cálcio, BHA, BHT. Ingredientes transgênicos. Espécies doadoras do gene: Bacillus thuringiensis; Streptomyces viridochromogenes; Agrobacterium tumefaciens; Zea mays.',
'71.99', 'Catbuddy\matissecarneadulto.png', 'Farmina Matisse para Gatos Adultos Carne e Arroz'),
(default, '1', 'Matisse Frango & Arroz é um alimento completo e balanceado para gatos adultos com nível de atividade física normal.
As proteínas são provenientes de ingredientes nobres de alto valor biológico e o cozimento ideal dos carboidratos fornecem alta digestibilidade. A cobertura e inserção de óleos e palatabilizantes a vácuo - sistema utilizado, atualmente, apenas pela Farmina no mercado Pet Brasileiro - torna o produto extremamente palatável e de imediata aceitação. Além disso, garante-se uma ótima relação de ácidos graxos ômega 6 e 3, essencial para a saúde da pele e do pelo.
Matisse Frango & Arroz contém quantidade ideal de taurina, importante aminoácido para o bom desempenho do miocárdio e da visão. A dieta é complementada pelo aporte de todas as vitaminas e minerais necessários para uma alimentação completa e balanceada.',
'25','2', 'Adulto', 'Frango e Arroz', '', '', '', 'farinha de vísceras de aves, quirera de arroz, grãos de milho, grãos de sorgo, farinha de peixe, óleo de frango, polpa de beterraba, óleo de peixe, glúten de milho-60, ovo desidratado, levedura seca de cervejaria, DL-metionina, taurina, hidrolisado de fígado de frango e suíno, vitaminas (A, D3, E, B1, B2, B6, B12, C, biotina, niacina, ácido pantotênico, ácido fólico, cloreto de colina), cloreto de sódio, cloreto de potássio, ácido fosfórico, sulfato ferroso, sulfato de cobre, sulfato de zinco, sulfato de manganês, selenito de sódio, iodato de cálcio, sulfato de cobalto, propionato de cálcio, BHA, BHT. Ingredientes transgênicos. Espécies doadoras do gene: Bacillus thuringiensis; Streptomyces viridochromogenes; Agrobacterium tumefaciens; Zea mays.',
'71.99', 'Catbuddy\matissefrangoadulto.png', 'Farmina Matisse para Gatos Adultos Frango e Arroz'),
(default, '1', 'Matisse Salmão & Arroz é um alimento completo e balanceado para gatos adultos com nível de atividade física normal.
As proteínas são provenientes de ingredientes nobres de alto valor biológico e o cozimento ideal dos carboidratos fornecem alta digestibilidade. A cobertura e inserção de óleos e palatabilizantes a vácuo - sistema utilizado, atualmente, apenas pela Farmina no mercado Pet Brasileiro - torna o produto extremamente palatável e de imediata aceitação. Além disso, garante-se uma ótima relação de ácidos graxos ômega 6 e 3, essencial para a saúde da pele e do pelo.
Matisse Salmão & Arroz contém quantidade ideal de taurina, importante aminoácido para o bom desempenho do miocárdio e da visão. A dieta é complementada pelo aporte de todas as vitaminas e minerais necessários para uma alimentação completa e balanceada.',
'31', '2', 'Adulto', 'Salmão e Arroz', '','','', 'farinha de peixe, farinha de vísceras de aves, quirera de arroz, grãos de milho, grãos de sorgo, óleo de frango, óleo de peixe, polpa de beterraba, glúten de milho-60, ovo desidratado, levedura seca de cervejaria, DL-metionina, taurina, hidrolisado de fígado de frango e suíno, vitaminas (A, D3, E, B1, B2, B6, B12, C, biotina, niacina, ácido pantotênico, ácido fólico, cloreto de colina), cloreto de sódio, cloreto de potássio, aditivo acidificante, sulfato ferroso, sulfato de cobre, sulfato de zinco, sulfato de manganês, selenito de sódio, iodato de cálcio, sulfato de cobalto, propionato de cálcio, BHA, BHT. Ingredientes transgênicos. Espécies doadoras do gene: Bacillus thuringiensis; Streptomyces viridochromogenes; Agrobacterium tumefaciens; Zea mays.',
'71.99', 'Catbuddy\matissesalmaoadulto.png', 'Farmina Matisse para Gatos Adultos Salmão e Arroz'),
(default, '1', 'Matisse Castrados Frango é um alimento completo e balanceado desenvolvido especialmente para atender as necessidades de gatos castrados. A castração traz mudanças importantes no metabolismo do gato e uma dieta adequada se faz necessária.
Por esse motivo, Matisse Castrados Frango foi formulado para auxiliar no controle do peso e, ao mesmo tempo, manter a massa muscular através de maior conteúdo de proteína e adição de carnitina.
Matisse Castrados Frango contém quantidade ideal de taurina, importante aminoácido para o bom desempenho do miocárdio e da visão. A dieta é complementada pelo aporte de todas as vitaminas e minerais necessários para uma alimentação completa e balanceada.',
'25', '2', 'Castrados', 'Frango', '', '', '', 'farinha de vísceras de aves, quirera de arroz, grãos de milho, grãos de sorgo, glúten de milho-60, casca de ervilha, celulose, farinha de peixe, óleo de frango, polpa de beterraba, óleo de peixe, ovo desidratado, farelo de trigo, levedura seca de cervejaria, DL-metionina, taurina, L-carnitina, hidrolisado de fígado de frango e suíno, vitaminas (A, D3, E, B1, B2, B6, B12, C, biotina, niacina, ácido pantotênico, ácido fólico, cloreto de colina), cloreto de sódio, cloreto de potássio, aditivo acidificante, sulfato ferroso, sulfato de cobre, sulfato de zinco, sulfato de manganês, selenito de sódio, iodato de cálcio, sulfato de cobalto, propionato de cálcio, BHA, BHT. Ingredientes transgênicos. Espécies doadoras do gene: Bacillus thuringiensis; Streptomyces viridochromogenes; Agrobacterium tumefaciens; Zea mays.',
'75.99', 'Catbuddy\matissecastradosfrango.png', 'Farmina Matisse para Gatos Castrados Frango'),
(default, '1', 'Matisse Castrados Salmão é um alimento completo e balanceado desenvolvido especialmente para atender as necessidades de gatos castrados. A castração traz mudanças importantes no metabolismo do gato e uma dieta adequada se faz necessária. Por esse motivo, Matisse Castrados Salmão foi formulado para auxiliar no controle do peso e, ao mesmo tempo, manter a massa muscular através de maior conteúdo de proteína e adição de carnitina.
Matisse Castrados Salmão contém quantidade ideal de taurina, importante aminoácido para o bom desempenho do miocárdio e da visão. A dieta é complementada pelo aporte de todas as vitaminas e minerais necessários para uma alimentação completa e balanceada.',
'25', '2', 'Castrados', 'Salmão', '', '', '', 'farinha de peixe, farinha de vísceras de aves, quirera de arroz, grãos de milho, grãos de sorgo, glúten de milho-60, ovo desidratado, farelo de trigo, casca de ervilha, celulose em pó, óleo de frango, polpa de beterraba, óleo de peixe, levedura seca de cervejaria, DL-metionina, taurina, L-carnitina, hidrolisado de fígado de frango e suíno, vitaminas (A, D3, E, B1, B2, B6, B12, C, biotina, niacina, ácido pantotênico, ácido fólico, cloreto de colina), cloreto de sódio, cloreto de potássio, aditivo acidificante, fosfato bicálcico, carbonato de cálcio, sulfato ferroso, sulfato de cobre, sulfato de zinco, sulfato de manganês, selenito de sódio, iodato de cálcio, sulfato de cobalto, propionato de cálcio, BHA, BHT. Ingredientes transgênicos. Espécies doadoras do gene: Bacillus thuringiensis; Streptomyces viridochromogenes; Agrobacterium tumefaciens; Zea mays.',
'75.99', 'Catbuddy\matissecastradossalmao.png', 'Farmina Matisse para Gatos Castrados Salmão'), 
(default, '1', 'Matisse Castrados Cordeiro é um alimento completo e balanceado desenvolvido especialmente para atender as necessidades de gatos castrados. A castração traz mudanças importantes no metabolismo do gato e uma dieta adequada se faz necessária. Por esse motivo, Matisse Castrados Cordeiro foi formulado para auxiliar no controle do peso e, ao mesmo tempo, manter a massa muscular através de maior conteúdo de proteína e adição de carnitina.
Matisse Castrados Cordeiro contém quantidade ideal de taurina, importante aminoácido para o bom desempenho do miocárdio e da visão. A dieta é complementada pelo aporte de todas as vitaminas e minerais necessários para uma alimentação completa e balanceada.',
'29', '2', 'Castrados', 'Cordeiro', '', '', '', 'farinha de carne e ossos de ovino, farinha de vísceras de aves, quirera de arroz, grãos de milho, grãos de sorgo, glúten de milho-60, ovo desidratado, farelo de trigo, casca de ervilha, celulose em pó, farinha de peixe, óleo de frango, polpa de beterraba, óleo de peixe, levedura seca de cervejaria, DL-metionina, taurina, L-carnitina, hidrolisado de fígado de frango e suíno, vitaminas (A, D3, E, B1, B2, B6, B12, C, biotina, niacina, ácido pantotênico, ácido fólico, cloreto de colina), cloreto de sódio, cloreto de potássio, aditivo acidificante, fosfato bicálcico, carbonato de cálcio, sulfato ferroso, sulfato de cobre, sulfato de zinco, sulfato de manganês, selenito de sódio, iodato de cálcio, sulfato de cobalto, propionato de cálcio, BHA, BHT. Ingredientes transgênicos. Espécies doadoras do gene: Bacillus thuringiensis; Streptomyces viridochromogenes; Agrobacterium tumefaciens; Zea mays.',
'75.99', 'Catbuddy\matissecarneadulto.png', 'Farmina Matisse para Gatos Castrados Cordeiro'),
(default, '1', 'Matisse Filhotes é um alimento completo e balanceado para gatos de 1 a 12 meses de idade. Devido ao seu alto valor nutricional, é também indicado para gatas gestantes ou em fase de amamentação.
A adequada nutrição do filhote é extremamente importante para seu correto desenvolvimento. Para isso, Matisse Filhotes foi especialmente desenvolvido com os melhores ingredientes para um crescimento saudável e equilibrado. A mistura de ingredientes, formulados harmoniosamente, garantem o nível calórico e proteico ideal para esta fase da vida dos gatos.
A cobertura e inserção de óleos e palatabilizantes a vácuo - sistema utilizado, atualmente, apenas pela Farmina no mercado Pet Brasileiro - torna o produto extremamente palatável e de imediata aceitação. Além disso, garante-se uma ótima relação de ácidos graxos ômega 6 e 3, essencial para a saúde da pele e do pelo.
Matisse Filhotes contém quantidade ideal de taurina, importante aminoácido para o bom desempenho do miocárdio e da visão. A dieta é complementada pelo aporte de todas as vitaminas e minerais necessários para uma alimentação completa e balanceada.',
'39', '2', 'Filhotes', 'Variados', '', '', '', 'farinha de vísceras de aves, quirera de arroz, grãos de milho, grãos de sorgo, óleo de frango, farinha de peixe, glúten de milho-60, ovo desidratado, polpa de beterraba, óleo de peixe, levedura seca de cervejaria, DL-metionina, taurina, hidrolisado de fígado de frango e suíno, vitaminas (A, D3, E, B1, B2, B6, B12, C, biotina, niacina, ácido pantotênico, ácido fólico, cloreto de colina), cloreto de sódio, cloreto de potássio, aditivo acidificante, sulfato ferroso, sulfato de cobre, sulfato de zinco, sulfato de manganês, selenito de sódio, iodato de cálcio, sulfato de cobalto, propionato de cálcio, BHA, BHT. Ingredientes transgênicos. Espécies doadoras do gene: Bacillus thuringiensis; Streptomyces viridochromogenes; Agrobacterium tumefaciens; Zea mays.',
'75.50', 'Catbuddy\matissefilhotes.png', 'Farmina Matisse para Gatos Filhotes');

insert into tbl_produto values -- premier seleção natural
(default, '1', 'Desenvolvida a partir de pesquisas científicas e alta tecnologia, PremieR Seleção Natural é uma linha inovadora que oferece em sua composição a exclusiva fonte de proteína Korin, complexo de 8 vegetais e ingredientes criteriosamente selecionados. A Korin segue a filosofia da Agricultura Natural, priorizando a saúde e o bem-estar animal, a sustentabilidade e o respeito ao meio ambiente. O frango Korin é criado sem o uso de antibióticos e promotores artificiais de crescimento, o que garante um produto rico em sabor, com a preservação de suas propriedades naturais. A PremieRpet e a Korin compartilham o preceito de excelência de seus produtos, através da qualidade de processos e matérias-primas, tecnologia de ponta e responsabilidade ambiental. Após 5 anos de parceria, o resultado não poderia ser diferente: um produto natural que traz reais benefícios à saúde do seu pet, proporcionando maior qualidade de vida e longevidade.',
'40', '1', 'Adultos', 'Frango', '', '', '', 'Farinha de vísceras de frango (Korin), farinha de torresmo, glúten de milho (não transgênico), ovo em pó, plasma sanguíneo desidratado de suíno, quirera de arroz, complexo de vegetais – 5,5% (beterraba, brócolis desidratado, cenoura, espinafre desidratado, polpa desidratada de beterraba e salsa desidratada), banha refinada, gordura de frango, óleo refinado de peixe, cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca, hidrolisado de fígado de suíno, parede celular de levedura (fonte de mananoligossacarídeos), sulfato de amônio, taurina, acetato de DL-alfa tocoferol, acetato de retinol, ácido ascórbico monofosfato, ácido fólico, ácido pantotênico, biotina, bissulfito de menadiona nicotinamida, cianocobalamina, cloreto de colina, colecalciferol, niacina (ácido nicotínico), piridoxina, riboflavina, tiamina, ferro aminoácido quelato, iodeto de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato.',
'79.80', 'Catbuddy\premierfrangoadultos.png', 'PremieR Seleção Natural Gatos Adultos Frango'),
(default, '1', 'Desenvolvida a partir de pesquisas científicas e alta tecnologia, PremieR Seleção Natural é uma linha inovadora, feita com ingredientes criteriosamente selecionados. Oferece em sua composição a exclusiva fonte de proteínas Korin, um diferenciado complexo de vegetais e ovos provenientes de galinhas livres de gaiolas (cage free).
A Korin segue a filosofia da Agricultura Natural, priorizando a saúde e o bem-estar animal, a sustentabilidade e o respeito ao meio ambiente. O frango Korin é criado sem o uso de antibióticos e promotores artificiais de crescimento, o que garante um produto rico em sabor, com a preservação de suas propriedades naturais.
PremieR Seleção Natural Gatos Castrados é recomendado para gatos castrados a partir de 6 meses de idade. Este produto oferece suporte às defesas naturais, promove o cuidado do trato urinário e auxilia no controle do peso, através de teores moderados de calorias e gorduras, além da L-carnitina que auxilia na conservação da massa muscular.
A combinação de ingredientes especiais com o alto aproveitamento dos nutrientes reduz o odor e volume das fezes, minimizando possíveis inconvenientes de uma vida dentro de casa.',
'38', '1', 'Castrados', 'Frango', '', '', '', 'Farinha de vísceras de frango (Korin), farinha de torresmo, glúten de milho (não transgênico), ovo em pó, proteína isolada de soja, quirera de arroz, aveia, complexo de vegetais – 7,0% (abóbora, alecrim, cenoura, extrato de marigold (Tagetes erecta), grão de quinoa, polpa desidratada de beterraba), farinha de mandioca, gordura de frango, óleo refinado de peixe, cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca (0,06%), hexametafosfato de sódio, hidrolisado de fígado de suíno, L-carnitina, parede celular de levedura (fonte de beta glucanas), parede celular de levedura (fonte de mananoligossacarídeos), sulfato de amônio, taurina, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B7, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina K3, ferro aminoácido quelato, iodato de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato.',
'79.80', 'Catbuddy\premierfrangocastrados.png', 'PremieR Seleção Natural Gatos Castrados Frango'),
(default, '1', 'Desenvolvida a partir de pesquisas científicas e alta tecnologia, PremieR Seleção Natural é uma linha inovadora que oferece em sua composição a exclusiva fonte de proteína Korin, complexo de 8 vegetais e ingredientes criteriosamente selecionados. A Korin segue a filosofia da Agricultura Natural, priorizando a saúde e o bem-estar animal, a sustentabilidade e o respeito ao meio ambiente. O frango Korin é criado sem o uso de antibióticos e promotores artificiais de crescimento, o que garante um produto rico em sabor, com a preservação de suas propriedades naturais. A PremieRpet e a Korin compartilham o preceito de excelência de seus produtos, através da qualidade de processos e matérias-primas, tecnologia de ponta e responsabilidade ambiental. Após 5 anos de parceria, o resultado não poderia ser diferente: um produto natural que traz reais benefícios à saúde do seu pet, proporcionando maior qualidade de vida e longevidade.',
'58', '1', 'Filhotes', 'Frango', '', '', '', 'Farinha de vísceras de frango (Korin), farinha de torresmo, glúten de milho (não transgênico), ovo em pó, plasma sanguíneo desidratado de suíno, quirera de arroz, complexo de vegetais – 5,5% (beterraba, brócolis desidratado, cenoura, espinafre desidratado, polpa desidratada de beterraba e salsa desidratada), banha refinada, gordura de frango, óleo refinado de peixe, cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca, frutooligossacarídeos, hidrolisado de fígado de suíno, parede celular de levedura (fonte de mananoligossacarídeos), sulfato de amônio, taurina, acetato de DL-alfa tocoferol, acetato de retinol, ácido ascórbico monofosfato, ácido fólico, ácido pantotênico, biotina, bissulfito de menadiona nicotinamida, cianocobalamina, cloreto de colina, colecalciferol, niacina (ácido nicotínico), piridoxina, riboflavina, tiamina, ferro aminoácido quelato, iodeto de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato.',
'79.80', 'Catbuddy\premierfrangofilhotes.png', 'PremieR Seleção Natural Gatos Filhotes Frango');

insert into tbl_produto values -- golden natural
(default, '1', 'Atenta às tendências do mercado e exigências dos nossos clientes, a PremieRpet lançou a nova linha GoldeN Seleção Natural, um alimento Premium Especial que mantém a reconhecida qualidade da Família GoldeN. Uma linha completa de produtos criada a partir da rigorosa seleção e controle de matéria-prima e formulada com ingredientes exclusivos. Contém complexo de 6 vegetais, como fonte de fibras e sais minerais, baixo teor de sódio para ressaltar o sabor natural dos ingredientes, sem corantes e aromatizantes artificiais e sem ingredientes transgênicos, a linha GoldeN Seleção Natural é a melhor escolha para que seu pet tenha uma alimentação de acordo com seu estilo de vida.',
'25', '1', 'Adultos', 'Frango e Arroz', '', '', '', 'Farinha de vísceras de frango, farinha de torresmo, glúten de milho (não transgênico), proteína isolada de soja, quirera de arroz, complexo de vegetais – 5,0% (beterraba, brócolis desidratado, cenoura, espinafre desidratado, polpa desidratada de beterraba e salsa desidratada), banha refinada, gordura de frango, óleo refinado de peixe, cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca (0,05%), hidrolisado de fígado de suíno, parede celular de levedura (fonte de mananoligossacarídeos), sulfato de amônio, taurina, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B7, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina K3, ferro aminoácido quelato, iodato de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato.',
'69.90', 'Catbuddy\gatosnaturalfrango.png', 'GoldeN Seleção Natural Gatos Adultos Frango e Arroz'),
(default, '1', 'Atenta às tendências do mercado e exigências dos nossos clientes, a PremieRpet lançou a nova linha GoldeN Seleção Natural, um alimento Premium Especial que mantém a reconhecida qualidade da Família GoldeN. Uma linha completa de produtos criada a partir da rigorosa seleção e controle de matéria-prima e formulada com ingredientes exclusivos. Contém nutrientes importantes para a saúde (ingredientes ricos em fibras e minerais), baixo teor de sódio para ressaltar o sabor natural dos ingredientes, sem corantes e aromatizantes artificiais e sem ingredientes transgênicos. GoldeN Seleção Natural Gatos Castrados Abóbora e Alecrim contém L-carnitina e teores reduzidos de calorias e gorduras para o controle de ganho de peso, além de minerais balanceados e controle do pH urinário para um trato urinário saudável.',
'50', '1', 'Castrados', 'Frango, abóbora e alecrim', '', '', '', 'Farinha de vísceras de frango, farinha de torresmo, glúten de milho (não transgênico), proteína isolada de soja, farinha de mandioca, quirera de arroz, complexo de vegetais – 6,8% (abóbora, alecrim, beterraba, cenoura, espinafre desidratado, polpa desidratada de beterraba e salsa desidratada), gordura de frango, óleo refinado de peixe, cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca (0,05%), hidrolisado de fígado de suíno, L-carnitina, sulfato de amônio, taurina, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B7, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina K3, ferro aminoácido quelato, iodato de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato.',
'69.90', 'Catbuddy\gatosnaturalfrangoabobora.png', 'GoldeN Seleção Natural Gatos Castrados Frango com Abóbora & Alecrim'),
(default, '1', 'Atenta às tendências do mercado e exigências dos nossos clientes, a linha GoldeN Seleção Natural, pertencente ao segmento Premium Especial, foi desenvolvida a partir de uma rigorosa seleção e controle de matérias-primas, além de ser formulada com ingredientes exclusivos. GoldeN Seleção Natural Gatos Castrados Sabor Frango com Batata Doce é indicado para gatos castrados a partir dos 6 meses de idade.
Este alimento contém nutrientes importantes para a saúde, como fontes de fibras e sais minerais e possui baixo teor de sódio para ressaltar o sabor natural dos ingredientes. Também auxilia no controle do ganho de peso, pois contém L-carnitina e teores reduzidos de calorias e gorduras, reduz o odor das fezes por meio de ingredientes especiais e é livre de corantes, aromatizantes artificiais e ingredientes transgênicos. GoldeN Seleção Natural, saudável como seu estilo de vida.',
'25', '1', 'Castrados', 'Frango e Batata Doce', '', '', '', 'Farinha de vísceras de frango, glúten de milho (não transgênico), quirera de arroz, aveia, complexo de vegetais – 6,0% (beterraba, brócolis desidratado, cenoura, espinafre desidratado, farinha de batata doce, polpa desidratada de beterraba, salsa desidratada), farinha de mandioca, gordura de frango, óleo refinado de peixe, cloreto de potássio, cloreto de sódio, levedura seca de cana de açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, difosfato trissódico, DL-metionina, extrato de yucca (0,05%), hidrolisado de fígado suíno, L-carnitina, sulfato de amônio, taurina, acetato de DL-alfa tocoferol, acetato de retinol, ácido ascórbico monofosfato, ácido fólico, ácido pantotênico, biotina, bissulfito de menadiona nicotinamida, cianocobalamina, cloreto de colina, colecalciferol, niacina (ácido nicotínico), piridoxina, riboflavina, tiamina, ferro aminoácido quelato, iodeto de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato.',
'69.90', 'Catbuddy\goldennaturalfbatata.png', 'GoldeN Seleção Natural Gatos Castrados Frango com Batata Doce'),
(default, '1', 'Atenta às tendências do mercado e exigências dos nossos clientes, a PremieRpet lançou a nova linha GoldeN Seleção Natural, um alimento Premium Especial que mantém a reconhecida qualidade da Família GoldeN. Uma linha completa de produtos criada a partir da rigorosa seleção e controle de matéria-prima e formulada com ingredientes exclusivos. Contém complexo de 6 vegetais, como fonte de fibras e sais minerais, baixo teor de sódio para ressaltar o sabor natural dos ingredientes, sem corantes e aromatizantes artificiais e sem ingredientes transgênicos, a linha GoldeN Seleção Natural é a melhor escolha para que seu pet tenha uma alimentação de acordo com seu estilo de vida. GoldeN Seleção Natural, saudável como seu estilo de vida.',
'32', '1', 'Filhotes', 'Frango e Arroz', '', '', '', 'Farinha de vísceras de frango, farinha de torresmo, glúten de milho (não transgênico), proteína isolada de soja, quirera de arroz, complexo de vegetais – 5,0% (beterraba, brócolis desidratado, cenoura, espinafre desidratado, polpa desidratada de beterraba e salsa desidratada), banha refinada, gordura de frango, óleo refinado de peixe, cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, difosfato (pirofosfato) trissódico, DL-metionina, extrato de yucca (0,05%), hidrolisado de fígado de suíno, parede celular de levedura (mananoligossacarídeos (0,20%)) taurina, sulfato de amônio, acetato de DL-alfa tocoferol, acetato de retinol, ácido ascórbico monofosfato, ácido fólico, ácido pantotênico, biotina, bissulfito de menadiona nicotinamida, cianocobalamina, cloreto de colina, colecalciferol, niacina (ácido nicotínico), piridoxina, riboflavina, tiamina, ferro aminoácido quelato, iodeto de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato.',
'69.90', 'Catbuddy\goldennaturalfilhtes.png', 'GoldeN Seleção Natural Gatos Filhotes Frango & Arroz');

insert into tbl_produto values -- golden
(default, '1', 'Formulada com ingredientes de alta qualidade e balanceada para suprir às particularidades nutricionais dos felinos, GoldeN Gatos Adultos Frango oferece sabor irresistível e cuidados especiais com o trato urinário, garantindo assim, sabor e saúde para seu gato.',
'60', '1', 'Adultos', 'Frango', '', '', '', 'Farinha de vísceras de frango, farinha de torresmo, glúten de milho, proteína concentrada de soja, grão de milho, quirera de arroz, polpa desidratada de beterraba, gordura de frango, biomassa de microalgas (Schizochytrium sp.), cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca (0,05%), hidrolisado de fígado de suíno, parede celular de levedura (fonte de mananoligossacarídeos), sulfato de amônio, taurina, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B7, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina K3, ferro aminoácido quelato, iodato de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato. Contém milho1, glúten de milho1 e proteína concentrada de soja2 transgênicos (espécies doadoras de gene: Bacillus thuringiensis1,2 e/ou Agrobacterium tumefaciens1,2 e/ou Streptomyces viridochromogenes1,2 e/ou Zea mays1 e/ou Arabidopsis Thaliana2 e/ou Agrobacterium tumefaciens/Bacillus thuringiensis2 e/ou Agrobacterium sp.2).',
'65.90', 'Catbuddy\goldenadultofrango.png', 'GoldeN Gatos Adultos Frango'),
(default, '1', 'Formulada com ingredientes de alta qualidade e balanceada para suprir às particularidades nutricionais dos felinos, GoldeN Gatos Adultos Salmão oferece sabor irresistível e cuidados especiais com o trato urinário, garantindo assim, sabor e saúde para seu gato.',
'62', '1', 'Adultos', 'Salmão', '', '', '', 'Farinha de vísceras de frango, farinha de salmão, glúten de milho, grão de milho, quirera de arroz, polpa desidratada de beterraba, gordura de frango, óleo refinado de peixe, cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca (0,05%), hidrolisado de fígado de suíno, parede celular de levedura (fonte de mananoligossacarídeos), taurina, sulfato de amônio, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B7, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina K3, ferro aminoácido quelato, iodeto de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato. Contém milho e glúten de milho transgênicos (espécies doadoras de gene: Bacillus thuringiensis e/ou Agrobacterium tumefaciens e/ou Streptomyces viridochromogenes e/ou Zea mays).',
'65.90', 'Catbuddy\goldenadultosalmao.png', 'GoldeN Gatos Adultos Salmão'),
(default, '1', 'Independentes, elegantes e exigentes, gatos são seres únicos que possuem particularidades fascinantes. Desde a forma como interagem com seu dono até seus hábitos durante a alimentação, todas as suas preferências devem ser percebidas e respeitadas. Entre suas peculiaridades nutricionais, está a maior exigência quanto ao sabor do alimento. Pensando nisso GoldeN Gatos Adultos Carne foi especialmente desenvolvido para agradar o paladar dos gatos, além de atender a todas as necessidades nutricionais para uma vida longa e saudável.',
'60', '1', 'Adultos', 'Carne', '', '', '', 'Farinha de vísceras de frango, farinha de carne e ossos de bovino, farinha de torresmo, glúten de milho, proteína concentrada de soja, grão de milho, quirera de arroz, polpa desidratada de beterraba, banha refinada, gordura de frango, biomassa de microalgas (Schizochytrium sp.), cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca (0,05%), hidrolisado de fígado de suíno, parede celular de levedura (fonte de mananoligossacarídeos), sulfato de amônio, taurina, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B7, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina K3, ferro aminoácido quelato, iodato de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato. Contém milho¹, glúten de milho1 e proteína concentrada de soja² transgênicos (espécies doadoras de gene: Bacillus thuringiensis1,2 e/ou Agrobacterium tumefaciens1,2 e/ou Streptomyces viridochromogenes1,2 e/ou Zea mays¹ e/ou Arabidopsis Thaliana² e/ou Agrobacterium tumefaciens/Bacillus thuringiensis² e/ou Agrobacterium sp.²).',
'65.90', 'Catbuddy\goldenadultoscarne.png', 'GoldeN Gatos Adultos Carne'),
(default, '1', 'Procedimento cada vez mais recomendado pelos médicos-veterinários, a castração promove inúmeros benefícios, mas também alterações fisiológicas que exigem alguns cuidados extras com a dieta do seu gato. Especialmente formulada para atender às necessidades dos gatos castrados, GoldeN Gatos Castrados Carne auxilia na prevenção da obesidade e no cuidado com o trato urinário, garantindo uma nutrição ótima e saudável.',
'65', '1', 'Castrados', 'Carne', '', '', '', 'Farinha de vísceras de frango, farinha de carne e ossos de bovino, farinha de torresmo, glúten de milho, glúten de trigo, proteína concentrada de soja, grão de milho, quirera de arroz, polpa desidratada de beterraba, gordura de frango, biomassa de microalgas (Schizochytrium sp.), cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca (0,05%), hidrolisado de fígado de suíno, L-carnitina, parede celular de levedura (fonte de mananoligossacarídeos), sulfato de amônio, taurina, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B7, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina K3, ferro aminoácido quelato, iodeto de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato. Contém milho1, glúten de milho1 e proteína concentrada de soja2 transgênicos (espécies doadoras de gene: Bacillus thuringiensis1,2 e/ou Agrobacterium tumefaciens1,2 e/ou Streptomyces viridochromogenes1,2 e/ou Zea mays1 e/ou Arabidopsis Thaliana2 e/ou Agrobacterium tumefaciens/Bacillus thuringiensis2 e/ou Agrobacterium sp.2).',
'65.90', 'Catbuddy\goldencastradocarne.png', 'GoldeN Gatos Castrados Carne'),
(default, '1', 'A castração promove inúmeros benefícios, mas também alterações fisiológicas que exigem alguns cuidados extras com a alimentação do seu gato. Pensando nisso, GoldeN Gatos Castrados Sabor Peixe é um alimento que auxilia no controle do ganho de peso, por meio da adição de L-carnitina e teores reduzidos de calorias e gorduras. Além disso, contribui para prevenção dos principais tipos de cálculos urinários utilizando o método SSR, tecnologia aplicada que proporciona um trato urinário saudável para o animal. O alimento também possui uma seleção de ingredientes especiais que permitem a redução do odor das fezes. Tudo isso garantindo nutrição ótima e saudável, com sabor inigualável. GoldeN Gatos Castrados Sabor Peixe é um alimento completo, balanceado e rico em nutrientes, indicado para gatos castrados a partir dos 6 meses de idade e contraindicado para filhotes de idade inferior a 6 meses, fêmeas gestantes e lactantes, devido ao seu reduzido teor calórico.',
'62', '1', 'Castrados', 'Peixe', '', '', '', 'Farinha de vísceras de frango, farinha de tilápia, glúten de milho, glúten de trigo, proteína concentrada de soja, grão de milho, quirera de arroz, farelo de arroz desengordurado, polpa desidratada de beterraba, gordura de frango, biomassa de microalgas (Schizochytrium sp.), cloreto de potássio, cloreto de sódio, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca (0,05%), hidrolisado de fígado de suíno, hidrolisado de peixes, L-carnitina, parede celular de levedura (fonte de mananoligossacarídeos), sulfato de amônio, taurina, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B7, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina K3, ferro aminoácido quelato, iodeto de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato. Contém milho1, glúten de milho1 e proteína concentrada de soja2 transgênicos (espécies doadoras de gene: Bacillus thuringiensis1,2 e/ou Agrobacterium tumefaciens1,2 e/ou Streptomyces viridochromogenes1,2 e/ou Zea mays1 e/ou Arabidopsis Thaliana2 e/ou Agrobacterium tumefaciens/Bacillus thuringiensis2 e/ou Agrobacterium sp.2).',
'65.90', 'Catbuddy\goldencastradopeixe.png', 'GoldeN Gatos Castrados Sabor Peixe'),
(default, '1', 'Procedimento cada vez mais recomendado pelos médicos-veterinários, a castração promove inúmeros benefícios, mas também alterações fisiológicas que exigem alguns cuidados extras com a dieta do seu gato. Especialmente formulada para atender às necessidades dos gatos castrados, GoldeN Gatos Castrados Salmão auxilia na prevenção da obesidade e no cuidado com o trato urinário, garantindo uma nutrição ótima e saudável.',
'60', '1', 'Castrados', 'Salmão', '', '', '', 'Farinha de vísceras de frango, farinha de salmão, farinha de torresmo, glúten de milho, glúten de trigo, proteína concentrada de soja, grão de milho, quirera de arroz, polpa desidratada de beterraba, gordura de frango, biomassa de microalgas (Schizochytrium sp.), cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca (0,05%), hidrolisado de fígado de suíno, L-carnitina, parede celular de levedura (fonte de mananoligossacarídeos), sulfato de amônio, taurina, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B7, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina K3, ferro aminoácido quelato, iodeto de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato. Contém milho1, glúten de milho1 e proteína concentrada de soja2 transgênicos (espécies doadoras de gene: Bacillus thuringiensis1,2 e/ou Agrobacterium tumefaciens1,2 e/ou Streptomyces viridochromogenes1,2 e/ou Zea mays1 e/ou Arabidopsis Thaliana2 e/ou Agrobacterium tumefaciens/Bacillus thuringiensis2 e/ou Agrobacterium sp.2).',
'65.90', 'Catbuddy\goldencastradosalmao.png', 'GoldeN Gatos Castrados Salmão'),
(default, '1', 'Procedimento cada vez mais recomendado pelos médicos-veterinários, a castração promove inúmeros benefícios, mas também alterações fisiológicas que exigem alguns cuidados extras com a dieta do seu gato. Especialmente formulada para atender às necessidades dos gatos castrados, GoldeN Gatos Castrados Frango auxilia na prevenção da obesidade e no cuidado com o trato urinário, garantindo uma nutrição ótima e saudável.',
'50', '1', 'Castrados', 'Frango', '', '', '', 'Farinha de vísceras de frango, farinha de torresmo, glúten de milho, glúten de trigo, proteína concentrada de soja, grão de milho, quirera de arroz, polpa desidratada de beterraba, gordura de frango, biomassa de microalgas (Schizochytrium sp.), cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca (0,05%), hidrolisado de fígado de suíno, L-carnitina, parede celular de levedura (fonte de mananoligossacarídeos), sulfato de amônio, taurina, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B7, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina K3, ferro aminoácido quelato, iodeto de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato. Contém milho¹, glúten de milho¹ e proteína concentrada de soja² transgênicos (espécies doadoras de gene: Bacillus thuringiensis1,2 e/ou Agrobacterium tumefaciens1,2 e/ou Streptomyces viridochromogenes1,2 e/ou Zea mays¹ e/ou Arabidopsis Thaliana² e/ou Agrobacterium tumefaciens/Bacillus thuringiensis² e/ou Agrobacterium sp.²).',
'65.90', 'Catbuddy\goldencastradosfrango.png', 'GoldeN Gatos Castrados Frango'),
(default, '1', 'Por entendermos que uma boa nutrição na infância é determinante para um adulto saudável é que desenvolvemos GoldeN Gatos Filhotes Frango. Perfeitamente balanceado, GoldeN Gatos Filhotes Frango atende por completo às necessidades de seu pequeno felino, oferecendo níveis ótimos de energia, proteínas, vitaminas e minerais, nutrientes indispensáveis para um desenvolvimento pleno e saudável.',
'80', '1', 'Filhotes', 'Frango', '', '', '', 'Farinha de vísceras de frango, farinha de torresmo, glúten de milho, grão de milho, quirera de arroz, polpa desidratada de beterraba, gordura de frango, óleo refinado de peixe, cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca (0,05%), hidrolisado de fígado de suíno, parede celular de levedura (fonte de mananoligossacarídeos), sulfato de amônio, taurina, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B7, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina K3, ferro aminoácido quelato, iodeto de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato. Contém milho e glúten de milho transgênicos (espécies doadoras de gene: Bacillus thuringiensis e/ou Agrobacterium tumefaciens e/ou Streptomyces viridochromogenes e/ou Zea Mays).',
'65.90', 'Catbuddy\goldencastradosfrango.png', 'GoldeN Gatos Filhotes Frango'),
(default, '1', 'GoldeN Special Gatos Adultos Sabor Frango e Carne é um alimento completo e balanceado para gatos adultos formulado com um blend de proteínas que permite máxima satisfação aos paladares mais exigentes. Ainda, contribui para prevenção dos principais tipos de cálculos urinários devido ao uso do método SSR, tecnologia aplicada que proporciona um trato urinário saudável para o animal. GoldeN Special Gatos Adultos Sabor Frango e Carne é um alimento de alta qualidade, rico em vitaminas e minerais e garante maior saúde e vitalidade ao pet. Não tem adição de corantes e aromatizantes artificiais. Além disso, também possui uma seleção de ingredientes especiais que permite a redução do odor das fezes.',
'30', '1', 'Adulto', 'Frango e Carne', '', '', '', 'Farinha de vísceras de frango, farinha de carne e ossos de bovino, glúten de milho, proteína concentrada de soja, grão de milho, quirera de arroz, farelo de arroz desengordurado, polpa desidratada de beterraba, gordura de frango, biomassa de microalgas (Schizochytrium sp.), cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca (0,05%), hexametafosfato de sódio, hidrolisado de fígado de suíno, sulfato de amônio, taurina, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B7, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina K3, iodeto de cálcio, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado. Contém milho1, glúten de milho1 e proteína concentrada de soja2 transgênicos (espécies doadoras de gene: Bacillus thuringiensis1,2 e/ou Agrobacterium tumefaciens1,2 e/ou Streptomyces viridochromogenes1,2 e/ou Zea mays1 e/ou Arabidopsis Thaliana2 e/ou Agrobacterium tumefaciens/Bacillus thuringiensis2 e/ou Agrobacterium sp.2).',
'55.99', 'Catbuddy\goldenadultosespecial.png', 'GoldeN Special Gatos Adultos Sabor Frango e Carne'),
(default, '1', 'A castração promove inúmeros benefícios, mas também alterações fisiológicas que exigem alguns cuidados extras com a alimentação do seu gato. Pensando nisso, GoldeN Special Gatos Castrados Sabor Frango e Carne é um alimento que auxilia no controle do ganho de peso, por meio de teores reduzidos de calorias e gorduras. Além disso, contribui para prevenção dos principais tipos de cálculos urinários utilizando o método SSR, tecnologia aplicada que proporciona um trato urinário saudável para o animal. O alimento também possui uma seleção de ingredientes especiais que permitem a redução do odor das fezes. Tudo isso garantindo nutrição ótima e saudável, com sabor inigualável. GoldeN Special Gatos Castrados Sabor Frango e Carne é um alimento completo, balanceado e rico em nutrientes, indicado para gatos castrados a partir dos 6 meses de idade e contraindicado para filhotes de idade inferior a 6 meses, fêmeas gestantes e lactantes, devido ao seu reduzido teor calórico.',
'25', '1', 'Castrados', 'Frango e Carne', '', '', '', 'Farinha de vísceras de frango, farinha de carne e ossos de bovino, glúten de milho, proteína concentrada de soja, grão de milho, quirera de arroz, farelo de arroz desengordurado, polpa desidratada de beterraba, gordura de frango, biomassa de microalgas (Schizochytrium sp.), cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca (0,05%), hexametafosfato de sódio, hidrolisado de fígado de suíno, sulfato de amônio, taurina, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B7, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina K3, iodeto de cálcio, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado. Contém milho1, glúten de milho1 e proteína concentrada de soja2 transgênicos (espécies doadoras de gene: Bacillus thuringiensis1,2 e/ou Agrobacterium tumefaciens1,2 e/ou Streptomyces viridochromogenes1,2 e/ou Zea mays1 e/ou Arabidopsis Thaliana2 e/ou Agrobacterium tumefaciens/Bacillus thuringiensis2 e/ou Agrobacterium sp.2).',
'55.99', 'Catbuddy\goldencastradosespecial.png', 'GoldeN Gatos Castrados Special Sabor Frango e Carne'),
(default, '1', 'GoldeN Gatos Castrados Senior foi especialmente formulada para atender às necessidades dos gatos castrados a partir de 10 anos de idade. Oferece um suporte nutricional adequado à idade, através de um balanço de nutrientes ajustado ao gato senior. Por ser rico em ômegas 3 e 6 e taurina, auxilia nos cuidados com a pele, pelagem, coração e visão. Promove ainda o cuidado com o trato urinário, garantindo uma nutrição ótima e saudável para esta fase da vida do animal.',
'30', '1', 'Senior', 'Frango, Arroz e Beterraba Branca', '', '', '', 'Farinha de vísceras de frango, farinha de torresmo, glúten de milho, glúten de trigo, proteína concentrada de soja, grão de milho, quirera de arroz, aveia, polpa desidratada de beterraba, gordura de frango, biomassa de microalgas (Schizochytrium sp.), cloreto de potássio, cloreto de sódio, levedura de cana-de-açúcar autolisada e desidratada, sulfato de glicosamina, ácido cítrico, bentonita, BHA (Butilhidroxianisol), BHT (Butilhidroxitolueno), cloreto de amônio, DL-metionina, extrato de yucca (0,05%), hidrolisado de fígado de suíno, parede celular de levedura (fonte de mananoligossacarídeos), sulfato de amônio, taurina, vitamina A, vitamina B1, vitamina B2, vitamina B3, vitamina B5, vitamina B6, vitamina B7, vitamina B9, vitamina B12, vitamina C, cloreto de colina, vitamina D3, vitamina E, vitamina K3, ferro aminoácido quelato, iodato de cálcio, manganês aminoácido quelato, selenometionina hidroxi análoga, sulfato de cobre pentahidratado, sulfato de ferro, sulfato de manganês, sulfato de zinco monohidratado, zinco aminoácido quelato. Contém milho1, glúten de milho1 e proteína concentrada de soja2 transgênicos (espécies doadoras de gene: Bacillus thuringiensis1,2 e/ou Agrobacterium tumefaciens1,2 e/ou Streptomyces viridochromogenes1,2 e/ou Zea mays1 e/ou Arabidopsis Thaliana2 e/ou Agrobacterium tumefaciens/Bacillus thuringiensis2 e/ou Agrobacterium sp.2).',
'55.99', 'Catbuddy\goldenseniorfrango.png', 'GoldeN Gatos Castrados Sênior Frango, Arroz e Beterraba Branca');


insert into tbl_produto values -- Whiskas
(default, '1', 'A Ração Whiskas Gatos Castrados Peixe é um alimento para gatos nutricionalmente completo e balanceado, com um ótimo equilíbrio de vitaminas e minerais para ajudá-lo a fornecer os melhores cuidados para o seu gato adulto. Ajuda na manutenção do peso ideal, receita sem corantes artificiais, desenvolvido com veterinários. Com probióticos que ajudam a proteger a saúde intestinal. Múltiplas fibras auxiliam no funcionamento gastrointestinal, contribuindo para bem-estar do seu gato.',
'25', '3', 'Castrados', 'Peixe', '', '', '', 'Farinha de Visceras e Ossos de Aves, Óleo de Peixe, Farinha de Carne e Ossos de bovinos, Glúten de Milho, Milho Integral, Farelo de Soja, Quirera de Arroz, , Gordura de Aves, Gordura de Ruminantes, Glúten de Trigo, Farinha de Trigo, Polpa desidratada de Beterraba, Cenoura, Espinafre, Hidrolisado de Fígado de Aves, Mananoligossacarídeo - mín 0.05%, Taurina, Metionina, Vitaminas (Vitamina A (Retinol), B1 (Tiamina), B2 (Riboflavina), B6 (Piridoxina), B12 (Cianocobalamina), D3 (Colecalciferol), E (Acetato DL Alfa Tocoferol), Ácido Fólico, Niacina, Cloreto de Colina, Ácido Pantotênico), Minerais (Cloreto de Potássio , Cloreto de Sódio (sal comum), Iodato de Cálcio, Óxido de Zinco, Selenito de Sódio, Sulfato de Cobre, Sulfato de Manganês), B.H.T. (Hidróxido de Tolueno Butilado).Eventuais Substitutivos: Sorgo Integral, Cevada em grão, Proteína Concentrada de Soja, Farinha de Salmão, Farinha de Carne e Ossos de Suíno, Celulose em Pó. Espécies doadoras de gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Zea mays, Sphingobium herbicidorovans, Dicossoma sp, Diabrotica firgifera, Thermoccocales spp, Bacillus subtilis. Espécies doadoras do gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Arabidopsis thaliana, Delftia acidovorans, Pseudomonas fluorescens, Zea mays, Stenotrophomonas maltophilia, B.T. var Azawai e Kurstaqui, Agrobacterium sp.',
'45.90', 'Catbuddy\whiskascastradopeixe.png', 'Whiskas Gatos Castrados Peixe'),
(default, '1', ' A Ração Whiskas Gatos Castrados Carne é um alimento para gatos nutricionalmente completo e balanceado, com um ótimo equilíbrio de vitaminas e minerais para ajudá-lo a fornecer os melhores cuidados para o seu gato adulto. As necessidades nutricionais do seu gato mudam ao longo do tempo. É por isso que o alimento seco para gatos Whiskas 1+ anos é especialmente desenvolvido para gatos curiosos proporcionando a eles todos os nutrientes e energia necessários para explorar o mundo. Deixe as refeições ainda mais saborosas com a linha de Whiskas que tem os sabores e texturas que seu pet irá amar. Mantenha sempre água fresca à disposição do seu gato, visite o veterinário regularmente.',
'69', '3', 'Castrados', 'Carne', '', '', '', 'Farinha de Carne e Ossos de bovinos, Farinha de Visceras e Ossos de Aves, Glúten de Milho, Milho Integral, Farelo de Soja, Quirera de Arroz, Gordura de Aves, Gordura de Ruminantes, Glúten de Trigo, Farinha de Trigo, Polpa desidratada de Beterraba, Cenoura, Espinafre, Hidrolisado de Fígado de Aves, Mananoligossacarídeo - mín 0.05%, Taurina, Metionina, Vitaminas (Vitamina A (Retinol), B1 (Tiamina), B2 (Riboflavina), B6 (Piridoxina), B12 (Cianocobalamina), D3 (Colecalciferol), E (Acetato DL Alfa Tocoferol), Ácido Fólico, Niacina, Cloreto de Colina, Ácido Pantotênico), Minerais (Cloreto de Potássio , Cloreto de Sódio (sal comum), Iodato de Cálcio, Óxido de Zinco, Selenito de Sódio, Sulfato de Cobre, Sulfato de Manganês), B.H.T. (Hidróxido de Tolueno Butilado).Eventuais Substitutivos: Sorgo Integral, Cevada em grão, Proteína Concentrada de Soja, Farinha de Carne e Ossos de Suíno, Celulose em Pó. Espécies doadoras de gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Zea mays, Sphingobium herbicidorovans, Dicossoma sp, Diabrotica firgifera, Thermoccocales spp, Bacillus subtilis. Espécies doadoras do gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Arabidopsis thaliana, Delftia acidovorans, Pseudomonas fluorescens, Zea mays, Stenotrophomonas maltophilia, B.T. var Azawai e Kurstaqui, Agrobacterium sp.',
'45.90', 'Catbuddy\whiskascastradocarne.png', 'Whiskas Gatos Castrados Carne'),
(default, '1', 'A Ração Whiskas Gatos Adultos Carne, uma opção de alimentação única que oferece uma nutrição completa e equilibrada para garantir o bem-estar do seu felino. Estes nuggets crocantes apresentam um recheio macio e saboroso, proporcionando uma experiência gastronômica irresistível. Enriquecida com Ômega 6 e Zinco, esta Ração para Gatos Adultos visa manter a pele e o pelo do seu gato saudáveis e brilhantes. Os probióticos adicionados contribuem para uma digestão saudável, enquanto o controle de minerais auxilia na manutenção do trato urinário em ótimo estado. Com uma combinação de fibras variadas, a Ração Whiskas promove a saúde gastrointestinal, garantindo um sistema digestivo equilibrado. Além disso, a Ração Whiskas 1+ é formulada com vitaminas e antioxidantes que fortalecem o sistema imunológico do seu gato. Desenvolvida em parceria com veterinários, a Ração Whiskas Carne oferece uma abordagem nutricionalmente balanceada para atender às necessidades específicas do seu companheiro felino.',
'50', '3', 'Adulto', 'Carne', '', '', '', 'Farinha de Carne e Ossos de bovinos, Farinha de Vísceras e Ossos de Aves, Glúten de Milho, Milho Integral, Farelo de Soja, Quirera de Arroz, Gordura de Aves, Gordura de Ruminantes, Glúten de Trigo, Farinha de Trigo, Cenoura, Espinafre, Hidrolisado de Fígado de Aves, Mananoligossacarídeo (mín 0.05%), Taurina, Metionina, Vitaminas (Vitamina A (Retinol), B1 (Tiamina), B2 (Riboflavina), B6 (Piridoxina), B12 (Cianocobalamina), D3 (Colecalciferol), E (Acetato DL Alfa Tocoferol), Ácido Fólico, Niacina, Cloreto de Colina, Ácido Pantotênico), Minerais (Cloreto de Potássio , Cloreto de Sódio (sal comum), Iodato de Cálcio, Óxido de Zinco, Selenito de Sódio, Sulfato de Cobre, Sulfato de Manganês), B.H.T. (Hidróxido de Tolueno Butilado), Corantes (Caramelo IV, Amarelo crepúsculo, Amarelo Tartrazina, Vermelho Ponceau 4R e Azul Indigotina).Eventuais Substitutivos: Sorgo Integral, Cevada em grão, Proteína Concentrada de Soja, Farinha de Carne e Ossos de Suíno. Espécies doadoras de gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Zea mays, Sphingobium herbicidorovans, Dicossoma sp, Diabrotica firgifera, Thermoccocales spp, Bacillus subtilis. Espécies doadoras do gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Arabidopsis thaliana, Delftia acidovorans, Pseudomonas fluorescens, Zea mays, Stenotrophomonas maltophilia, B.T. var Azawai e Kurstaqui, Agrobacterium sp',
'49.90', 'Catbuddy\whiskasadultocarne.png', 'Whiskas Gatos Adultos Carne'),
(default, '1', 'A Ração Whiskas Peixe Gatos Adultos, uma opção nutricionalmente completa formulada para o bem-estar do seu felino. Com equilíbrio ideal de vitaminas e minerais, essa fórmula atende às necessidades específicas dos gatos adultos. Desenvolvida para gatos de 1 ano ou mais, a Whiskas peixe oferece nutrientes essenciais para uma vida ativa. Livre de corantes artificiais, enfatiza a qualidade dos ingredientes para uma experiência alimentar natural. A fórmula da ração whiskas peixe contribui para a saúde urinária, contendo taurina, vitaminas e minerais essenciais. Enriquecida com Ômega 6 e zinco, promove a saúde da pele e pelagem do seu gato, garantindo uma aparência vibrante.',
'58', '3', 'Adulto', 'Peixe', '', '', '', 'Farinha de Visceras e Ossos de Aves, Óleo de Peixe, Glúten de Milho, Milho Integral, Farelo de Soja, Farinha de Carne e Ossos de bovinos, Quirera de Arroz, Gordura de Aves, Gordura de Ruminantes, Glúten de Trigo, Farinha de Trigo, Cenoura, Espinafre, Hidrolisado de Fígado de Aves, Mananoligossacarídeo - mín 0.05%, Taurina, Metionina, Vitaminas (Vitamina A (Retinol), B1 (Tiamina), B2 (Riboflavina), B6 (Piridoxina), B12 (Cianocobalamina), D3 (Colecalciferol), E (Acetato DL Alfa Tocoferol), Ácido Fólico, Niacina, Cloreto de Colina, Ácido Pantotênico), Minerais (Cloreto de Potássio , Cloreto de Sódio (sal comum), Iodato de Cálcio, Óxido de Zinco, Selenito de Sódio, Sulfato de Cobre, Sulfato de Manganês), B.H.T. (Hidróxido de Tolueno Butilado), Corantes (Caramelo IV, Amarelo crepúsculo, Amarelo Tartrazina, Vermelho Ponceau 4R e Azul Indigotina).Eventuais Substitutivos: Sorgo Integral, Cevada em grão, Proteína Concentrada de Soja, Farinha de Salmão, Farinha de Carne e Ossos de Suíno. Espécies doadoras de gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Zea mays, Sphingobium herbicidorovans, Dicossoma sp, Diabrotica firgifera, Thermoccocales spp, Bacillus subtilis. Espécies doadoras do gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Arabidopsis thaliana, Delftia acidovorans, Pseudomonas fluorescens, Zea mays, Stenotrophomonas maltophilia, B.T. var Azawai e Kurstaqui, Agrobacterium sp',
'49.90',  'Catbuddy\whiskasadultopeixe.png', 'Whiskas Gatos Adultos Peixe'),
(default, '1', 'Desenvolvida junto com médicos-veterinários, a ração Whiskas de frango reúne um ótimo equilíbrio de vitaminas e minerais, sem deixar de lado os sabores e texturas que o seu gato irá amar. Como as necessidades nutricionais do seu gato mudam ao longo do tempo, a Ração Whiskas frango é adequada para a fase adulta dos felinos, ou seja, com mais de 1 ano de idade. Especialmente formulada para proporcionar a eles energia e todos os nutrientes necessários para o dia a dia.',
'56','3', 'Adulto', 'Frango', '', '', '', 'Farinha de Visceras e Ossos de Aves, Glúten de Milho, Milho Integral, Farelo de Soja, Farinha de Carne e Ossos de bovinos, Quirera de Arroz, Gordura de Aves, Gordura de Ruminantes, Glúten de Trigo, Farinha de Trigo, Cenoura, Espinafre, Hidrolisado de Fígado de Aves, Mananoligossacarídeo - mín 0.05%, Taurina, Metionina, Vitaminas (Vitamina A (Retinol), B1 (Tiamina), B2 (Riboflavina), B6 (Piridoxina), B12 (Cianocobalamina), D3 (Colecalciferol), E (Acetato DL Alfa Tocoferol), Ácido Fólico, Niacina, Cloreto de Colina, Ácido Pantotênico), Minerais (Cloreto de Potássio , Cloreto de Sódio (sal comum), Iodato de Cálcio, Óxido de Zinco, Selenito de Sódio, Sulfato de Cobre, Sulfato de Manganês), B.H.T. (Hidróxido de Tolueno Butilado).Eventuais Substitutivos: Sorgo Integral, Cevada em grão, Proteína Concentrada de Soja, Farinha de Carne e Ossos de Suíno. Espécies doadoras de gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Zea mays, Sphingobium herbicidorovans, Dicossoma sp, Diabrotica firgifera, Thermoccocales spp, Bacillus subtilis. Espécies doadoras do gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Arabidopsis thaliana, Delftia acidovorans, Pseudomonas fluorescens, Zea mays, Stenotrophomonas maltophilia, B.T. var Azawai e Kurstaqui, Agrobacterium sp',
'49.90', 'Catbuddy\whiskasadultofrango.png', 'Whiskas Gatos Adultos Frango'),
(default, '1', 'A Whiskas aumentou seu portfólio de alimentos desenvolvidos especialmente para gatos com a linha Melhor Por Natureza. Uma ração seca com ingredientes recomendados pelo Centro de Pesquisas Waltham, uma das principais autoridades mundiais quando o assunto é nutrição animal. Na composição Whiskas Natureza tem: linhaça (fonte de Ômega 3), crocantes nuggets recheados, fibra de beterraba e 100% da proteína é de fornecedores certificados. Buscando uma alimentação completa e balanceada para o seu gato? Então, você precisa conhecer a ração Whiskas Melhor Por Natureza. Ela combina nutrientes, vitaminas e minerais em uma ração premium especial no sabor salmão.',
'29', '3', 'Adulto', 'Salmão', '', '', '', 'Farinha de Vísceras e Ossos de Aves, Farinha de Carne e Ossos de bovinos, Farinha de Salmão, Glúten de Milho, Glúten de Trigo, Quirera de Arroz, Milho Integral, Farelo de Soja, Gordura de Aves, Gordura de Ruminantes, Farinha de Trigo, Polpa de Beterraba (2%), Linhaça (0,5%), Canjica de Milho, Taurina, Metionina, Hidrolisado de Fígado de Aves, Vitaminas (Vitamina A (retinol), B1 (tiamina), B2 (riboflavina), B6 (piridoxina), B12 (cianocobalamina), D3 (colecalciferol), E (acetato DL alfa tocoferol), K (Menadiona Bissulfito de Sódio), Ácido Fólico, Niacina, Biotina, Cloreto de Colina, Ácido Pantotênico), Minerais (Cloreto de Potássio , Cloreto de Sódio – sal comum –, Iodato de Cálcio, Óxido de Zinco, Selenito de Sódio), B.H.T. (Hidróxido de Tolueno Butilado).Eventuais Substitutivos: Sorgo Integral Moído, Cevada em grão, Trigo Integral, Farinha de Carne e Ossos de Suíno Espécies doadoras de gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Zea mays, Sphingobium herbicidorovans, Dicossoma sp, Diabrotica firgifera, Thermoccocales spp, Bacillus substilis. Espécies doadoras do gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Arabidopsis thaliana, Delftia acidovorans, Pseudomonas fluorescens, Zea mays, Stenotrophomonas maltophilia, B.T. var Azawai e Kurstaqui, Agrobacterium sp',
'59.90', 'Catbuddy\whiskasadultosalmaoespecial.png', 'Whiskas Gatos Adultos Melhor Por Natureza Salmão'),
(default, '1', 'O Novo Whiskas Melhor Por Natureza tem receitas deliciosas, incluindo ingredientes naturais que seu gato precisa para sua saúde. Alimento para gatos adultos, nutricionalmente completo e balanceado, com um ótimo equilíbrio de vitaminas e minerais para ajudá-lo a fornecer os melhores cuidados para o seu gato adulto. Contém fibra de beterraba que ajuda na digestão e função intestinal saudável. Contém linhaça, fonte natural de ômega 3. Ração Anti Bola de Pelo, com fibras naturais que auxiliam na eliminação de bolas de pelos, e deliciosos e crocantes nuggests recheados que seu gato ama. Sem corantes ou aromas artificiais, e receitas com 100% de proteína de fornecedores certificados.',
'25', '3', 'Adulto', 'Frango', '', '', '', 'Farinha de Vísceras e Ossos de Aves, Farinha de Carne e Ossos de bovinos, Glúten de Milho, Glúten de Trigo, Quirera de Arroz, Milho Integral, Farelo de Soja, Gordura de Aves, Gordura de Ruminantes, Farinha de Trigo, Polpa de Beterraba (2%), Linhaça (0,5%), Canjica de Milho, Taurina, Metionina, Hidrolisado de Fígado de Aves, Vitaminas (Vitamina A (retinol), B1 (tiamina), B2 (riboflavina), B6 (piridoxina), B12 (cianocobalamina), D3 (colecalciferol), E (acetato DL alfa tocoferol), K (Menadiona Bissulfito de Sódio), Ácido Fólico, Niacina, Biotina, Cloreto de Colina, Ácido Pantotênico), Minerais (Cloreto de Potássio , Cloreto de Sódio – sal comum –, Iodato de Cálcio, Óxido de Zinco, Selenito de Sódio), B.H.T. (Hidróxido de Tolueno Butilado).Eventuais Substitutivos: Sorgo Integral, Cevada em grão, Trigo Integral, Farinha de Carne e Ossos de Suíno Espécies doadoras de gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Zea mays, Sphingobium herbicidorovans, Dicossoma sp, Diabrotica firgifera, Thermoccocales spp, Bacillus substilis. Espécies doadoras do gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Arabidopsis thaliana, Delftia acidovorans, Pseudomonas fluorescens, Zea mays, Stenotrophomonas maltophilia, B.T. var Azawai e Kurstaqui, Agrobacterium sp',
'59.90', 'Catbuddy\whiskasadultofrangoespecial.png', 'Whiskas Gatos Adultos Melhor Por Natureza Frango'),
(default, '1', 'A Ração Whiskas Gatos Filhotes Carne e Leite é uma opção premium para gatos filhotes de 2 a 12 meses, desenvolvida para atender às necessidades nutricionais cruciais durante essa fase. Com um sabor delicioso de carne e leite, essa fórmula equilibrada proporciona uma experiência gastronômica irresistível, garantindo um desenvolvimento saudável. Elaborada em colaboração com veterinários, essa ração para gatos filhotes é adaptada para oferecer suporte nutricional personalizado durante o crescimento do seu pet. Com pedaços pequenos, prebióticos para digestão saudável e DHA para o desenvolvimento cerebral, é uma escolha confiável para promover um início de vida saudável. Além do sabor excepcional, a ração Whiskas gatos filhotes oferece benefícios nutricionais abrangentes. Com controle de minerais para a saúde do trato urinário e uma mistura de vitaminas e antioxidantes para reforçar o sistema imunológico, é uma escolha confiável para garantir que seu gato filhote cresça forte e saudável desde os primeiros meses de vida.',
'59', '3', 'Filhote', 'Carne e Leite', '', '', '', 'Farinha de Visceras e Ossos de Aves, Glúten de Milho, Milho Integral, Farelo de Soja, Farinha de Carne e Ossos de Bovinos, Quirera de Arroz, Gordura de Aves, Leite em Pó, Óleo de Peixe, Cenoura, Espinafre, Hidrolisado de Fígado de Aves, Mananoligossacarídeo - mín 0.05%, Taurina, Metionina, Vitaminas (Vitamina A (Retinol), B1 (Tiamina), B2 (Riboflavina), B6 (Piridoxina), B12 (Cianocobalamina), D3 (Colecalciferol), E (Acetato DL Alfa Tocoferol), Ácido Fólico, Niacina, Cloreto de Colina, Ácido Pantotênico), Minerais (Cloreto de Potássio , Cloreto de Sódio (sal comum), Iodato de Cálcio, Óxido de Zinco, Selenito de Sódio, Sulfato de Cobre, Sulfato de Manganês), B.H.T. (Hidróxido de Tolueno Butilado).Eventuais Substitutivos: Sorgo Integral, Cevada em grão, Trigo Integral, Farinha de Peixe, Proteína Concentrada de Soja, Biomassa de microalga, Farinha de Carne e Ossos de Suíno Espécies doadoras de gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Zea mays, Sphingobium herbicidorovans, Dicossoma sp, Diabrotica firgifera, Thermoccocales spp, Bacillus subtilis.Espécies doadoras do gene: Agrobacterium tumefaciens, Bacillus thuringiensis, Streptomyces viridochromogenes, Arabidopsis thaliana, Delftia acidovorans, Pseudomonas fluorescens, Zea mays, Stenotrophomonas maltophilia, B.T. var Azawai e Kurstaqui, Agrobacterium sp',
'49.90', 'Catbuddy\whiskasadultofrangoespecial.png', 'Whiskas Gatos Filhotes Carne e Leite');

-- Remove o prefixo "Catbuddy" de todos os produtos 
update tbl_produto set imgpath = REPLACE (imgpath, "Catbuddy", "") where imgpath like "Catbuddy%";

-- Coloca o prefixo do projeto
update tbl_produto set imgpath = CONCAT("img/produtos/", imgpath);

insert into tbl_usuario value(null, 1, "ROBESVALDO", "57812365478");